---
galaxy_info:
  author: velez
  description: Core system setup for workstation configuration
  company: Personal
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Fedora
      versions:
        - 36
        - 37
        - 38
    - name: EL
      versions:
        - 8
        - 9
  galaxy_tags:
    - system
    - configuration
    - workstation
    - users

dependencies: []