# Core system setup playbook for general use
- hosts: localhost
  connection: local
  gather_facts: true

  pre_tasks:
    - name: update repositories (Ubuntu/Debian)
      tags: always
      become: true
      apt: update_cache=yes
      changed_when: False
      when: ansible_facts["os_family"] == "Debian"

    - name: update repositories (Fedora/RHEL)
      tags: always
      become: true
      dnf:
        update_cache: yes
      changed_when: False
      when: ansible_facts["os_family"] == "RedHat"

    - name: update repositories (Arch Linux)
      tags: always
      become: true
      community.general.pacman:
        update_cache: yes
      changed_when: False
      when: ansible_facts["os_family"] == "Archlinux"

  roles:
    - core