# Development system setup playbook
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories (Ubuntu/Debian)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_os_family == "Debian"

    - name: update repositories (Fedora/RHEL)
      tags: always
      dnf:
        update_cache: yes
      changed_when: False
      when: ansible_os_family == "RedHat"

  roles:
    - dev