# tasks to complete before running roles
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      tags: always
      apt: update_cache=yes
      changed_when: False

  roles:
    - name: roles
    - base

