---

- name: users | create ansible user
  user:
    name: ansible
    groups: sudo
    append: yes
    state: present

- name: users | add ansible ssh key
  authorized_key:
    user: ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExkp/21VsASdw1ujck9XolFvfNGqqqUqbXHpM0RNbJo ansible deploy"

- name: users | copy sudoers_ansible
  copy:
    src: users/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: users | create velez user
  user:
    name: velez
    groups: sudo
    append: yes
    state: present

- name: users | add velez ssh key
  authorized_key:
    user: velez
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOH+GDuX+7RjQhBp5CM0vJRH6s91BrYvm4boNyt6MTPr velez identity"

