- name: users | create velez user
  user:
    name: velez
    groups: adm,ansible,sudo
    append: yes
    state: present
    shell: /bin/zsh

- name: users | ssh | add velez ssh key
  authorized_key:
    user: velez
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOH+GDuX+7RjQhBp5CM0vJRH6s91BrYvm4boNyt6MTPr velez identity"

#- name: users | sudo | copy sudoers_velez
#  copy:
#    src: users/sudoers_velez
#    dest: /etc/sudoers.d/velez
#    owner: root
#    group: root
#    mode: 0440

# configure software
- name: users | tmux | copy tmux.conf
  copy:
    src: system_setup/tmux.conf
    dest: /home/velez/.tmux.conf
    owner: velez
    group: velez
    mode: 0644


- name: users | vim | copy .vimrc
  copy:
    src: system_setup/vimrc
    dest: /home/velez/.vim/
    owner: velez
    group: velez
    mode: 0644

- name: users | zsh | copy .zshrc
  copy:
    src: system_setup/zshrc
    dest: /home/velez/.zshrc
    owner: velez
    group: velez
    mode: 0644

