- block:
  - name: system setup | utilities | add universe repository
    apt_repository:
      repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
      state: present
#  - name: system setup | utilities | add powerline
#   package:
#     state: present
#     name:
#     - powerline
#     - fonts-powerline
  when: ansible_distribution == 'Ubuntu'



- name: system setup | utilities | install utility packages 
  tags: packages,system,settings
  package:
    state: latest
    name:
      - htop
      - mc
      - tmux
      - wget
      - zsh

