#- debug:
#    msg: "base role - i am herer"

- block:
  # install users
  - import_tasks: users/ansible.yml
  - import_tasks: users/velez.yml

- block:
  # install software
  - import_tasks: software/packages_utilities.yml

  # configure software
  - import_tasks: system_setup/cron.yml

